-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2025-05-18 02:11:59 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE dostawa (
    id            NUMBER NOT NULL,
    data_dostawy  DATE,
    status        VARCHAR2(50),
    zamowienie_id NUMBER NOT NULL
)
LOGGING;

ALTER TABLE dostawa ADD CONSTRAINT dostawa_pk PRIMARY KEY ( id );

CREATE TABLE karta_biblioteczna (
    id            NUMBER NOT NULL,
    numer_karty   VARCHAR2(50),
    data_wydania  DATE,
    data_waznosci DATE,
    status        VARCHAR2(50),
    uzytkownik_id NUMBER NOT NULL
)
LOGGING;

ALTER TABLE karta_biblioteczna ADD CONSTRAINT karta_biblioteczna_pk PRIMARY KEY ( id );

CREATE TABLE ksiazka (
    id           NUMBER NOT NULL,
    tytul        VARCHAR2(255),
    autor        VARCHAR2(255),
    data_wydania DATE,
    wydawnictwo  VARCHAR2(255),
    typ_okladki  VARCHAR2(50),
    gatunek      VARCHAR2(100),
    status       VARCHAR2(50)
)
LOGGING;

ALTER TABLE ksiazka ADD CONSTRAINT ksiazka_pk PRIMARY KEY ( id );

CREATE TABLE magazyn (
    id          NUMBER NOT NULL,
    ilosc       NUMBER,
    lokalizacja VARCHAR2(100),
    ksiazka_id  NUMBER NOT NULL
)
LOGGING;

ALTER TABLE magazyn ADD CONSTRAINT magazyn_pk PRIMARY KEY ( id );

CREATE TABLE pozycja_dostawy (
    id         NUMBER NOT NULL,
    ilosc      NUMBER,
    ksiazka_id NUMBER NOT NULL,
    dostawa_id NUMBER NOT NULL
)
LOGGING;

ALTER TABLE pozycja_dostawy ADD CONSTRAINT pozycja_dostawy_pk PRIMARY KEY ( id );

CREATE TABLE pozycja_zamowienia (
    id            NUMBER NOT NULL,
    ilosc         NUMBER,
    ksiazka_id    NUMBER NOT NULL,
    zamowienie_id NUMBER NOT NULL
)
LOGGING;

ALTER TABLE pozycja_zamowienia ADD CONSTRAINT pozycja_zamowienia_pk PRIMARY KEY ( id );

CREATE TABLE raport (
    id             NUMBER NOT NULL,
    typ            VARCHAR2(50),
    data_generacji DATE,
    zawartosc      CLOB,
    uzytkownik_id  NUMBER NOT NULL
)
LOGGING;

ALTER TABLE raport ADD CONSTRAINT raport_pk PRIMARY KEY ( id );

CREATE TABLE rezerwacja (
    id               NUMBER NOT NULL,
    data_rezerwacji  DATE,
    data_wygasniecia DATE,
    status           VARCHAR2(50),
    uzytkownik_id    NUMBER NOT NULL,
    ksiazka_id       NUMBER NOT NULL
)
LOGGING;

ALTER TABLE rezerwacja ADD CONSTRAINT rezerwacja_pk PRIMARY KEY ( id );

CREATE TABLE uczestnik_wydarzenia (
    id            NUMBER NOT NULL,
    uzytkownik_id NUMBER NOT NULL,
    wydarzenie_id NUMBER NOT NULL
)
LOGGING;

ALTER TABLE uczestnik_wydarzenia ADD CONSTRAINT uczestnik_wydarzenia_pk PRIMARY KEY ( id );

CREATE TABLE uzytkownik (
    id               NUMBER NOT NULL,
    imie             VARCHAR2(100),
    nazwisko         VARCHAR2(100),
    email            VARCHAR2(255),
    haslo            VARCHAR2(255),
    typ_uzytkownika  VARCHAR2(50) DEFAULT 'czytelnik' NOT NULL,
    data_rejestracji TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
LOGGING;

ALTER TABLE uzytkownik ADD CONSTRAINT uzytkownik_pk PRIMARY KEY ( id );

CREATE TABLE wydarzenie (
    id      NUMBER NOT NULL,
    temat   VARCHAR2(255),
    data    DATE,
    godzina VARCHAR2(10),
    miejsce VARCHAR2(255)
)
LOGGING;

ALTER TABLE wydarzenie ADD CONSTRAINT wydarzenie_pk PRIMARY KEY ( id );

CREATE TABLE wypozyczenie (
    id                      NUMBER NOT NULL,
    data_wypozyczenia       DATE,
    planowana_data_zwrotu   DATE,
    rzeczywista_data_zwrotu DATE,
    kara                    NUMBER(10, 2),
    uzytkownik_id           NUMBER NOT NULL,
    ksiazka_id              NUMBER NOT NULL
)
LOGGING;

ALTER TABLE wypozyczenie ADD CONSTRAINT wypozyczenie_pk PRIMARY KEY ( id );

CREATE TABLE zamowienie (
    id                NUMBER NOT NULL,
    dostawca          VARCHAR2(255),
    data_zamowienia   DATE,
    termin_realizacji DATE,
    status            VARCHAR2(50)
)
LOGGING;

ALTER TABLE zamowienie ADD CONSTRAINT zamowienie_pk PRIMARY KEY ( id );

ALTER TABLE dostawa
    ADD CONSTRAINT dostawa_zamowienie_fk FOREIGN KEY ( zamowienie_id )
        REFERENCES zamowienie ( id )
    NOT DEFERRABLE;

ALTER TABLE karta_biblioteczna
    ADD CONSTRAINT karta_biblioteczna_uzytkownik_fk FOREIGN KEY ( uzytkownik_id )
        REFERENCES uzytkownik ( id )
    NOT DEFERRABLE;

ALTER TABLE magazyn
    ADD CONSTRAINT magazyn_ksiazka_fk FOREIGN KEY ( ksiazka_id )
        REFERENCES ksiazka ( id )
    NOT DEFERRABLE;

ALTER TABLE pozycja_dostawy
    ADD CONSTRAINT pozycja_dostawy_dostawa_fk FOREIGN KEY ( dostawa_id )
        REFERENCES dostawa ( id )
    NOT DEFERRABLE;

ALTER TABLE pozycja_dostawy
    ADD CONSTRAINT pozycja_dostawy_ksiazka_fk FOREIGN KEY ( ksiazka_id )
        REFERENCES ksiazka ( id )
    NOT DEFERRABLE;

ALTER TABLE pozycja_zamowienia
    ADD CONSTRAINT pozycja_zamowienia_ksiazka_fk FOREIGN KEY ( ksiazka_id )
        REFERENCES ksiazka ( id )
    NOT DEFERRABLE;

ALTER TABLE pozycja_zamowienia
    ADD CONSTRAINT pozycja_zamowienia_zamowienie_fk FOREIGN KEY ( zamowienie_id )
        REFERENCES zamowienie ( id )
    NOT DEFERRABLE;

ALTER TABLE raport
    ADD CONSTRAINT raport_uzytkownik_fk FOREIGN KEY ( uzytkownik_id )
        REFERENCES uzytkownik ( id )
    NOT DEFERRABLE;

ALTER TABLE rezerwacja
    ADD CONSTRAINT rezerwacja_ksiazka_fk FOREIGN KEY ( ksiazka_id )
        REFERENCES ksiazka ( id )
    NOT DEFERRABLE;

ALTER TABLE rezerwacja
    ADD CONSTRAINT rezerwacja_uzytkownik_fk FOREIGN KEY ( uzytkownik_id )
        REFERENCES uzytkownik ( id )
    NOT DEFERRABLE;

ALTER TABLE uczestnik_wydarzenia
    ADD CONSTRAINT uczestnik_wydarzenia_uzytkownik_fk FOREIGN KEY ( uzytkownik_id )
        REFERENCES uzytkownik ( id )
    NOT DEFERRABLE;

ALTER TABLE uczestnik_wydarzenia
    ADD CONSTRAINT uczestnik_wydarzenia_wydarzenie_fk FOREIGN KEY ( wydarzenie_id )
        REFERENCES wydarzenie ( id )
    NOT DEFERRABLE;

ALTER TABLE wypozyczenie
    ADD CONSTRAINT wypozyczenie_ksiazka_fk FOREIGN KEY ( ksiazka_id )
        REFERENCES ksiazka ( id )
    NOT DEFERRABLE;

ALTER TABLE wypozyczenie
    ADD CONSTRAINT wypozyczenie_uzytkownik_fk FOREIGN KEY ( uzytkownik_id )
        REFERENCES uzytkownik ( id )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
