DELETE FROM Wypozyczenie;
DELETE FROM Uczestnik_Wydarzenia;
DELETE FROM Rezerwacja;
DELETE FROM Raport;
DELETE FROM Karta_Biblioteczna;
DELETE FROM Dostawa;
DELETE FROM Magazyn;
DELETE FROM Zamowienie_Ksiazka;
DELETE FROM Zamowienie;
DELETE FROM Ksiazka;
DELETE FROM Wydarzenie;
DELETE FROM Dostawca;
DELETE FROM Uzytkownik;
DELETE FROM Wydawnictwo;
DELETE FROM Typ_Okladki;
DELETE FROM Autor;
DELETE FROM Rola;
DELETE FROM Biblioteka_Ksiazka;

DROP TABLE Biblioteka_Ksiazka;
DROP TABLE Wypozyczenie;
DROP TABLE Uczestnik_Wydarzenia;
DROP TABLE Rezerwacja;
DROP TABLE Raport;
DROP TABLE Karta_Biblioteczna;
DROP TABLE Dostawa;
DROP TABLE Magazyn;
DROP TABLE Zamowienie_Ksiazka;
DROP TABLE Zamowienie;
DROP TABLE Ksiazka;
DROP TABLE Wydarzenie;
DROP TABLE Dostawca;
DROP TABLE Uzytkownik;
DROP TABLE Wydawnictwo;
DROP TABLE Typ_Okladki;
DROP TABLE Autor;
DROP TABLE Rola;

CREATE TABLE Rola (
    Rola_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nazwa VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE Autor (
    Autor_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Imie VARCHAR2(50),
    Nazwisko VARCHAR2(50)
);

CREATE TABLE Typ_Okladki (
    Typ_Okladki_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nazwa VARCHAR2(50) NOT NULL
);

CREATE TABLE Wydawnictwo (
    Wydawnictwo_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nazwa VARCHAR2(100) NOT NULL
);

CREATE TABLE Ksiazka (
    Ksiazka_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Tytul VARCHAR2(255) NOT NULL,
    Autor_ID NUMBER NOT NULL,
    ISBN VARCHAR2(20),
    Data_Wydania DATE,
    Wydawnictwo_ID NUMBER,
    Typ_Okladki_ID NUMBER,
    FOREIGN KEY (Autor_ID) REFERENCES Autor(Autor_ID),
    FOREIGN KEY (Wydawnictwo_ID) REFERENCES Wydawnictwo(Wydawnictwo_ID),
    FOREIGN KEY (Typ_Okladki_ID) REFERENCES Typ_Okladki(Typ_Okladki_ID)
);

CREATE TABLE Uzytkownik (
    Uzytkownik_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Imie VARCHAR2(50),
    Nazwisko VARCHAR2(50),
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Telefon VARCHAR2(20),
    Haslo VARCHAR2(255) NOT NULL,
    Rola_ID NUMBER NOT NULL,
    FOREIGN KEY (Rola_ID) REFERENCES Rola(Rola_ID)
);

CREATE TABLE Dostawca (
    Dostawca_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nazwa VARCHAR2(100) NOT NULL
);

CREATE TABLE Zamowienie (
    Zamowienie_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Uzytkownik_ID NUMBER NOT NULL,
    Dostawca_ID NUMBER NOT NULL,
    Ilosc NUMBER NOT NULL,
    Data_Zamowienia DATE DEFAULT CURRENT_DATE,
    Termin_Realizacji DATE,
    Status VARCHAR2(25) DEFAULT 'Nowe',
    FOREIGN KEY (Uzytkownik_ID) REFERENCES Uzytkownik(Uzytkownik_ID),
    FOREIGN KEY (Dostawca_ID) REFERENCES Dostawca(Dostawca_ID)
);

CREATE TABLE Zamowienie_Ksiazka (
    Zamowienie_Ksiazka_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Zamowienie_ID NUMBER NOT NULL,
    Ksiazka_ID NUMBER NOT NULL,
    Ilosc NUMBER NOT NULL,
    FOREIGN KEY (Zamowienie_ID) REFERENCES Zamowienie(Zamowienie_ID),
    FOREIGN KEY (Ksiazka_ID) REFERENCES Ksiazka(Ksiazka_ID)
);

CREATE TABLE Magazyn (
    Magazyn_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ksiazka_ID NUMBER NOT NULL,
    Ilosc NUMBER DEFAULT 0,
    Sektor NUMBER,
    Rzad NUMBER,
    Polka NUMBER,
    MiejsceNaPolce NUMBER,
    FOREIGN KEY (Ksiazka_ID) REFERENCES Ksiazka(Ksiazka_ID)
);

CREATE TABLE Dostawa (
    Dostawa_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Zamowienie_Ksiazka_ID NUMBER NOT NULL,
    Data_Dostawy DATE DEFAULT CURRENT_DATE,
    Ilosc NUMBER NOT NULL,
    Status VARCHAR2(25) DEFAULT 'Oczekujaca',
    FOREIGN KEY (Zamowienie_Ksiazka_ID) REFERENCES Zamowienie_Ksiazka(Zamowienie_Ksiazka_ID)
);

CREATE TABLE Karta_Biblioteczna (
    Karta_Biblioteczna_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Numer_Karty VARCHAR2(50),
    Data_Wydania DATE,
    Data_Waznosci DATE,
    Status VARCHAR2(50),
    Uzytkownik_ID NUMBER NOT NULL,
    FOREIGN KEY (Uzytkownik_ID) REFERENCES Uzytkownik(Uzytkownik_ID)
);

CREATE TABLE Raport (
    Raport_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Typ VARCHAR2(50),
    Data_Generacji DATE,
    Zawartosc CLOB,
    Uzytkownik_ID NUMBER NOT NULL,
    FOREIGN KEY (Uzytkownik_ID) REFERENCES Uzytkownik(Uzytkownik_ID)
);

CREATE TABLE Rezerwacja (
    Rezerwacja_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data_Rezerwacji DATE,
    Data_Wygasniecia DATE,
    Status VARCHAR2(50),
    Uzytkownik_ID NUMBER NOT NULL,
    Ksiazka_ID NUMBER NOT NULL,
    FOREIGN KEY (Uzytkownik_ID) REFERENCES Uzytkownik(Uzytkownik_ID),
    FOREIGN KEY (Ksiazka_ID) REFERENCES Ksiazka(Ksiazka_ID)
);

CREATE TABLE Wydarzenie (
    Wydarzenie_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Temat VARCHAR2(255),
    Data DATE,
    Godzina VARCHAR2(10),
    Miejsce VARCHAR2(255)
);

CREATE TABLE Uczestnik_Wydarzenia (
    Uczestnik_Wydarzenia_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Uzytkownik_ID NUMBER NOT NULL,
    Wydarzenie_ID NUMBER NOT NULL,
    FOREIGN KEY (Uzytkownik_ID) REFERENCES Uzytkownik(Uzytkownik_ID),
    FOREIGN KEY (Wydarzenie_ID) REFERENCES Wydarzenie(Wydarzenie_ID)
);

CREATE TABLE Wypozyczenie (
    Wypozyczenie_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data_Wypozyczenia DATE,
    Planowana_Data_Zwrotu DATE,
    Rzeczywista_Data_Zwrotu DATE,
    Kara NUMBER(10, 2),
    Uzytkownik_ID NUMBER NOT NULL,
    Ksiazka_ID NUMBER NOT NULL,
    FOREIGN KEY (Uzytkownik_ID) REFERENCES Uzytkownik(Uzytkownik_ID),
    FOREIGN KEY (Ksiazka_ID) REFERENCES Ksiazka(Ksiazka_ID)
);

CREATE TABLE Biblioteka_Ksiazka (
    Egzemplarz_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ksiazka_ID NUMBER NOT NULL,
    Status VARCHAR2(50) DEFAULT 'Dostepna',
    Lokalizacja VARCHAR2(100),
    FOREIGN KEY (Ksiazka_ID) REFERENCES Ksiazka(Ksiazka_ID)
);

COMMIT;